# Utiliser une image Python officielle comme base
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier du serveur
COPY tcp_server.py /app

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port du serveur
EXPOSE 54320

# Commande à exécuter lorsque le conteneur démarre
CMD ["python", "tcp_server.py"]
