services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: les-loups
    volumes:
      - ./wv_views.sql:/docker-entrypoint-initdb.d/wv_schemas.sql
    ports:
      - "5432:5432"
    

  administration:
    build: ./moteur-administration
    depends_on:
      - db
    # command: pip install -r requirements.txt